[2025-06-02T23:36:36.004+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-02T23:35:54.331508+00:00 [queued]>
[2025-06-02T23:36:36.022+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-02T23:35:54.331508+00:00 [queued]>
[2025-06-02T23:36:36.023+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-02T23:36:36.045+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_y_validacion> on 2025-06-02 23:35:54.331508+00:00
[2025-06-02T23:36:36.076+0000] {standard_task_runner.py:57} INFO - Started process 184 to run task
[2025-06-02T23:36:36.091+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto-final', 'training_modelos_y_validacion', 'manual__2025-06-02T23:35:54.331508+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto-final.py', '--cfg-path', '/tmp/tmpo3cgiuua']
[2025-06-02T23:36:36.099+0000] {standard_task_runner.py:85} INFO - Job 94: Subtask training_modelos_y_validacion
[2025-06-02T23:36:36.227+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-02T23:35:54.331508+00:00 [running]> on host fe73afd4d10b
[2025-06-02T23:36:36.470+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto-final' AIRFLOW_CTX_TASK_ID='training_modelos_y_validacion' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T23:35:54.331508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T23:35:54.331508+00:00'
[2025-06-02T23:36:42.363+0000] {logging_mixin.py:149} WARNING - 2025/06/02 23:36:42 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-06-02T23:36:42.694+0000] {logging_mixin.py:149} WARNING - 2025/06/02 23:36:42 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-02T23:36:44.016+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-06-02T23:36:53.322+0000] {logging_mixin.py:149} WARNING - 2025/06/02 23:36:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-06-02T23:36:54.024+0000] {logging_mixin.py:149} WARNING - Registered model 'Regresion_Lineal_modelo_produccion' already exists. Creating a new version of this model...
[2025-06-02T23:36:54.139+0000] {logging_mixin.py:149} WARNING - 2025/06/02 23:36:54 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: Regresion_Lineal_modelo_produccion, version 6
[2025-06-02T23:36:54.140+0000] {logging_mixin.py:149} WARNING - Created version '6' of model 'Regresion_Lineal_modelo_produccion'.
[2025-06-02T23:36:54.395+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-02T23:36:54.420+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto-final, task_id=training_modelos_y_validacion, execution_date=20250602T233554, start_date=20250602T233636, end_date=20250602T233654
[2025-06-02T23:36:54.537+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-02T23:36:54.579+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
