[2025-06-03T00:03:03.775+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-03T00:02:16.424722+00:00 [queued]>
[2025-06-03T00:03:03.795+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-03T00:02:16.424722+00:00 [queued]>
[2025-06-03T00:03:03.796+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-03T00:03:03.819+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_y_validacion> on 2025-06-03 00:02:16.424722+00:00
[2025-06-03T00:03:03.837+0000] {standard_task_runner.py:57} INFO - Started process 557 to run task
[2025-06-03T00:03:03.847+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto-final', 'training_modelos_y_validacion', 'manual__2025-06-03T00:02:16.424722+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto-final.py', '--cfg-path', '/tmp/tmphqozd0u3']
[2025-06-03T00:03:03.852+0000] {standard_task_runner.py:85} INFO - Job 98: Subtask training_modelos_y_validacion
[2025-06-03T00:03:03.950+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-03T00:02:16.424722+00:00 [running]> on host fe73afd4d10b
[2025-06-03T00:03:04.097+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto-final' AIRFLOW_CTX_TASK_ID='training_modelos_y_validacion' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T00:02:16.424722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T00:02:16.424722+00:00'
[2025-06-03T00:03:11.258+0000] {logging_mixin.py:149} INFO - 0.015208354417341169
[2025-06-03T00:03:11.281+0000] {logging_mixin.py:149} INFO - 0.6698276246637168
[2025-06-03T00:03:11.282+0000] {logging_mixin.py:149} INFO - Data drift en 'bed' con distancia Wasserstein = 0.6698
[2025-06-03T00:03:11.310+0000] {logging_mixin.py:149} INFO - 0.6734731477606025
[2025-06-03T00:03:11.311+0000] {logging_mixin.py:149} INFO - Data drift en 'bath' con distancia Wasserstein = 0.6735
[2025-06-03T00:03:11.365+0000] {logging_mixin.py:149} INFO - 0.009688305042472572
[2025-06-03T00:03:11.409+0000] {logging_mixin.py:149} INFO - 0.10859994231356597
[2025-06-03T00:03:11.410+0000] {logging_mixin.py:149} INFO - Data drift en 'house_size' con distancia Wasserstein = 0.1086
[2025-06-03T00:03:12.652+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:03:12 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-06-03T00:03:13.119+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:03:13 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-03T00:03:14.717+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-06-03T00:03:22.688+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:03:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-06-03T00:03:23.628+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

[2025-06-03T00:03:23.698+0000] {logging_mixin.py:149} WARNING - Registered model 'Regresion_Lineal_modelo_produccion' already exists. Creating a new version of this model...
[2025-06-03T00:03:23.803+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:03:23 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: Regresion_Lineal_modelo_produccion, version 7
[2025-06-03T00:03:23.803+0000] {logging_mixin.py:149} WARNING - Created version '7' of model 'Regresion_Lineal_modelo_produccion'.
[2025-06-03T00:03:23.943+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-03T00:03:23.966+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto-final, task_id=training_modelos_y_validacion, execution_date=20250603T000216, start_date=20250603T000303, end_date=20250603T000323
[2025-06-03T00:03:24.065+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-03T00:03:24.105+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
